-- ============================================================================
-- MAP SHR Data → Cold Case Platform SQL Loader
-- Generated by map_importer.py
--
-- Usage:  psql -d coldcase -f load_map_data.sql
-- Prereq: NDJSON files in same directory
-- ============================================================================

BEGIN;

CREATE TEMP TABLE _raw_json (doc JSONB);

-- ── 1. CASES ────────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/map_cases.ndjson'

INSERT INTO cases (
    id, title, slug, status, date_occurred,
    location_city, location_state, location_country,
    primary_agency, jurisdiction, summary,
    crime_type, crime_subtypes,
    victim_name, victim_age_at_time
)
SELECT
    (doc->>'id')::UUID,
    doc->>'title',
    doc->>'slug',
    (doc->>'status')::case_status,
    (doc->>'date_occurred')::DATE,
    doc->>'location_city',
    doc->>'location_state',
    COALESCE(doc->>'location_country', 'US'),
    doc->>'primary_agency',
    doc->>'jurisdiction',
    doc->>'summary',
    doc->>'crime_type',
    ARRAY(SELECT jsonb_array_elements_text(doc->'crime_subtypes')),
    doc->>'victim_name',
    (doc->>'victim_age_at_time')::INTEGER
FROM _raw_json
ON CONFLICT (slug) DO NOTHING;

TRUNCATE _raw_json;

-- ── 2. SOURCES ──────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/map_sources.ndjson'

INSERT INTO sources (
    id, url, domain, title, source_type,
    reliability_rating, content_hash
)
SELECT
    (doc->>'id')::UUID,
    doc->>'url',
    doc->>'domain',
    doc->>'title',
    (doc->>'source_type')::source_type,
    (doc->>'reliability_rating')::INTEGER,
    doc->>'content_hash'
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 3. ENTITIES ─────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/map_entities.ndjson'

INSERT INTO entities (
    id, entity_type, canonical_name, aliases, summary,
    attributes, first_seen_date, last_seen_date,
    is_identified, is_alive
)
SELECT
    (doc->>'id')::UUID,
    (doc->>'entity_type')::entity_type,
    doc->>'canonical_name',
    COALESCE(ARRAY(SELECT jsonb_array_elements_text(doc->'aliases')), '{}'),
    doc->>'summary',
    COALESCE((doc->'attributes')::JSONB, '{}'::JSONB),
    (doc->>'first_seen_date')::DATE,
    (doc->>'last_seen_date')::DATE,
    (doc->>'is_identified')::BOOLEAN,
    (doc->>'is_alive')::BOOLEAN
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 4. EVIDENCE ─────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/map_evidence.ndjson'

INSERT INTO evidence (
    id, case_id, evidence_code, title, summary,
    category, confidence, evidence_date,
    source_id, source_detail, ingestion_method, tags, metadata
)
SELECT
    (doc->>'id')::UUID,
    (doc->>'case_id')::UUID,
    doc->>'evidence_code',
    doc->>'title',
    doc->>'summary',
    (doc->>'category')::evidence_category,
    (doc->>'confidence')::confidence_level,
    (doc->>'evidence_date')::DATE,
    (doc->>'source_id')::UUID,
    doc->>'source_detail',
    (doc->>'ingestion_method')::ingestion_method,
    ARRAY(SELECT jsonb_array_elements_text(doc->'tags')),
    COALESCE((doc->'metadata')::JSONB, '{}'::JSONB)
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 5. ENTITY_EVIDENCE ─────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/map_entity_evidence.ndjson'

INSERT INTO entity_evidence (
    id, entity_id, evidence_id, role, first_mentioned
)
SELECT
    (doc->>'id')::UUID,
    (doc->>'entity_id')::UUID,
    (doc->>'evidence_id')::UUID,
    (doc->>'role')::entity_role,
    (doc->>'first_mentioned')::BOOLEAN
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 6. CONNECTIONS (victim-offender relationships) ──────────────────────────

\copy _raw_json(doc) FROM 'output/map_connections.ndjson'

INSERT INTO connections (
    id, entity_a_id, entity_b_id, relationship,
    confidence, description
)
SELECT
    (doc->>'id')::UUID,
    (doc->>'entity_a_id')::UUID,
    (doc->>'entity_b_id')::UUID,
    (doc->>'relationship')::relationship_type,
    (doc->>'confidence')::confidence_level,
    doc->>'description'
FROM _raw_json
ON CONFLICT DO NOTHING;

DROP TABLE _raw_json;

COMMIT;

-- Verify counts
SELECT 'cases' AS tbl, COUNT(*) FROM cases WHERE crime_type = 'homicide'
UNION ALL SELECT 'entities', COUNT(*) FROM entities
UNION ALL SELECT 'sources', COUNT(*) FROM sources WHERE domain = 'murderdata.org'
UNION ALL SELECT 'evidence', COUNT(*) FROM evidence WHERE 'map' = ANY(tags);
