-- ============================================================================
-- Charley Project → Cold Case Platform SQL Loader
-- Generated by charley_scraper.py
-- 
-- Usage:  psql -d coldcase -f load_charley_data.sql
-- Prereq: NDJSON files in same directory (or adjust paths)
-- ============================================================================

BEGIN;

-- ── Helper: load NDJSON into a temp table ───────────────────────────────────

CREATE TEMP TABLE _raw_json (doc JSONB);

-- ── 1. CASES ────────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/cases.ndjson'

INSERT INTO cases (
    id, title, slug, status, date_occurred,
    location_city, location_state, location_country,
    primary_agency, summary, crime_type, crime_subtypes,
    victim_name, victim_age_at_time, victim_dob
)
SELECT
    (doc->>'id')::UUID,
    doc->>'title',
    doc->>'slug',
    (doc->>'status')::case_status,
    (doc->>'date_occurred')::DATE,
    doc->>'location_city',
    doc->>'location_state',
    COALESCE(doc->>'location_country', 'US'),
    doc->>'primary_agency',
    doc->>'summary',
    doc->>'crime_type',
    ARRAY(SELECT jsonb_array_elements_text(doc->'crime_subtypes')),
    doc->>'victim_name',
    (doc->>'victim_age_at_time')::INTEGER,
    (doc->>'victim_dob')::DATE
FROM _raw_json
ON CONFLICT (slug) DO UPDATE SET
    summary = EXCLUDED.summary,
    primary_agency = COALESCE(EXCLUDED.primary_agency, cases.primary_agency),
    updated_at = NOW();

TRUNCATE _raw_json;

-- ── 2. SOURCES ──────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/sources.ndjson'

INSERT INTO sources (
    id, url, domain, title, source_type, reliability_rating,
    cached_text, content_hash
)
SELECT
    (doc->>'id')::UUID,
    doc->>'url',
    doc->>'domain',
    doc->>'title',
    (COALESCE(doc->>'source_type', 'website'))::source_type,
    (doc->>'reliability_rating')::INTEGER,
    doc->>'cached_text',
    doc->>'content_hash'
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 3. ENTITIES ─────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/entities.ndjson'

INSERT INTO entities (
    id, entity_type, canonical_name, aliases, summary,
    attributes, first_seen_date, last_seen_date,
    is_identified, is_alive
)
SELECT
    (doc->>'id')::UUID,
    (doc->>'entity_type')::entity_type,
    doc->>'canonical_name',
    ARRAY(SELECT jsonb_array_elements_text(doc->'aliases')),
    doc->>'summary',
    (doc->'attributes')::JSONB,
    (doc->>'first_seen_date')::DATE,
    (doc->>'last_seen_date')::DATE,
    (doc->>'is_identified')::BOOLEAN,
    (doc->>'is_alive')::BOOLEAN
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 4. EVIDENCE ─────────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/evidence.ndjson'

INSERT INTO evidence (
    id, case_id, evidence_code, title, summary, full_text,
    category, confidence, evidence_date,
    source_id, source_detail, ingestion_method,
    raw_source_id, tags
)
SELECT
    (doc->>'id')::UUID,
    (doc->>'case_id')::UUID,
    doc->>'evidence_code',
    doc->>'title',
    doc->>'summary',
    doc->>'full_text',
    (doc->>'category')::evidence_category,
    (doc->>'confidence')::confidence_level,
    (doc->>'evidence_date')::DATE,
    (doc->>'source_id')::UUID,
    doc->>'source_detail',
    (doc->>'ingestion_method')::ingestion_method,
    (doc->>'raw_source_id')::UUID,
    ARRAY(SELECT jsonb_array_elements_text(doc->'tags'))
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 5. ENTITY_EVIDENCE ─────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/entity_evidence.ndjson'

INSERT INTO entity_evidence (
    id, entity_id, evidence_id, role, first_mentioned
)
SELECT
    (doc->>'id')::UUID,
    (doc->>'entity_id')::UUID,
    (doc->>'evidence_id')::UUID,
    (doc->>'role')::entity_role,
    (doc->>'first_mentioned')::BOOLEAN
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 6. RAW_STAGING ──────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/raw_staging.ndjson'

INSERT INTO raw_staging (
    id, source_url, source_domain, content_type,
    content_hash, scrape_status, scraped_at
)
SELECT
    (doc->>'id')::UUID,
    doc->>'source_url',
    doc->>'source_domain',
    doc->>'content_type',
    doc->>'content_hash',
    (doc->>'scrape_status')::scrape_status,
    (doc->>'scraped_at')::TIMESTAMPTZ
FROM _raw_json
ON CONFLICT DO NOTHING;

TRUNCATE _raw_json;

-- ── 7. SCRAPE_JOBS ──────────────────────────────────────────────────────────

\copy _raw_json(doc) FROM 'output/scrape_jobs.ndjson'

INSERT INTO scrape_jobs (
    id, target_url, target_domain, target_type, case_id,
    status, started_at, completed_at, pages_scraped,
    raw_staging_id, is_recurring, recurrence_interval
)
SELECT
    (doc->>'id')::UUID,
    doc->>'target_url',
    doc->>'target_domain',
    (doc->>'target_type')::source_type,
    (doc->>'case_id')::UUID,
    (doc->>'status')::scrape_status,
    (doc->>'started_at')::TIMESTAMPTZ,
    (doc->>'completed_at')::TIMESTAMPTZ,
    (doc->>'pages_scraped')::INTEGER,
    (doc->>'raw_staging_id')::UUID,
    (doc->>'is_recurring')::BOOLEAN,
    (doc->>'recurrence_interval')::INTERVAL
FROM _raw_json
ON CONFLICT DO NOTHING;

DROP TABLE _raw_json;

COMMIT;

-- Verify counts
SELECT 'cases' AS tbl, COUNT(*) FROM cases
UNION ALL SELECT 'entities', COUNT(*) FROM entities
UNION ALL SELECT 'sources', COUNT(*) FROM sources
UNION ALL SELECT 'evidence', COUNT(*) FROM evidence;
